import "./globals.css";
import { Inter, Montserrat, Lato } from "next/font/google";
// import { Session } from 'next-auth'
// import { SessionProvider } from "next-auth/react";
// import Provider from "./provider";
import "tailwindcss/tailwind.css";

export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});
export const lato = Lato({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
          {children}

      </body>
    </html>
  );
}
